[build]
command = "npm run build"
publish = "dist"

# ---- apps variant ----
[[redirects]]
from = "/apps/dark-mode-color-palette-generator"
to   = "/index.html"
status = 200

[[redirects]]
from = "/apps/dark-mode-color-palette-generator/assets/*"
to   = "/assets/:splat"
status = 200

[[redirects]]
from = "/apps/dark-mode-color-palette-generator/*"
to   = "/index.html"
status = 200

# ---- embed variant ----

[[redirects]]
from = "/embed/dark-mode-color-palette-generator"
to   = "/embed.html"
status = 200

[[redirects]]
from = "/embed/dark-mode-color-palette-generator/*"
to   = "/embed.html"
status = 200